FROM apache/spark:3.5.1-scala2.12-java11-ubuntu

USER root

# MODIFICATIONS GO HERE
COPY assembly/target/datatunnel-3.5.0/*.jar /opt/spark/jars/
COPY kyuubi-extension-spark-3-5_2.12-1.9.1.jar /opt/spark/jars/
COPY minio-8.5.11.jar /opt/spark/jars/

# EMRS will run the image as hadoop
USER hadoop:hadoop
