FROM public.ecr.aws/emr-serverless/spark/emr-6.15.0:latest

USER root
# MODIFICATIONS GO HERE
ADD assembly/target/datatunnel-3.4.0.tar.gz /usr/lib/spark/jars/

# EMRS will run the image as hadoop
USER hadoop:hadoop