FROM public.ecr.aws/emr-serverless/spark/emr-7.9.0:latest

USER root

# 瑞幸需要的python lib
RUN pip3 install mysql-connector-python pycryptodome pytz python-dateutil -U -i https://pypi.tuna.tsinghua.edu.cn/simple

# 删除 emr 自带的jar
RUN rm -f /usr/lib/spark/jars/spark-redshift*

ADD assembly/target/datatunnel-3.5.0.tar.gz /usr/lib/
RUN cp /usr/lib/datatunnel-3.5.0/*.jar /usr/lib/spark/jars/ \
    && rm -rf /usr/lib/datatunnel-3.5.0

RUN curl -o /usr/lib/spark/jars/kyuubi-extension-spark-3-5_2.12-1.11.1.jar -L https://repo1.maven.org/maven2/org/apache/kyuubi/kyuubi-extension-spark-3-5_2.12/1.11.1/kyuubi-extension-spark-3-5_2.12-1.11.1.jar

# EMRS will run the image as hadoop
USER hadoop:hadoop
